version: "3.7"
services:
    db:
        image: mariadb:10.1.38
        ports:
            - "13306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: messenger-monitor

    redis:
        image: redis
        ports:
            - "6379:6379"

    rabbitmq:
        image: rabbitmq:3.7.17-management
        ports:
            - "5672:5672"
            - "15672:15672"
